SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CW1].[Features](
	[FeaturesID] [int] IDENTITY(1,1) NOT NULL,
	[Feature] [varchar](20) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [CW1].[Features] ADD PRIMARY KEY CLUSTERED 
(
	[FeaturesID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [CW1].[Features]  WITH CHECK ADD CHECK  (([Feature]=(upper(left([Feature],(1)))+substring([Feature],(2),len([Feature])))))
GO
