SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CW1].[TrailFeatures](
	[Trail_ID] [int] NOT NULL,
	[Feature_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [CW1].[TrailFeatures] ADD PRIMARY KEY CLUSTERED 
(
	[Trail_ID] ASC,
	[Feature_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [CW1].[TrailFeatures]  WITH CHECK ADD FOREIGN KEY([Feature_ID])
REFERENCES [CW1].[Features] ([Feature_ID])
GO
ALTER TABLE [CW1].[TrailFeatures]  WITH CHECK ADD FOREIGN KEY([Trail_ID])
REFERENCES [CW1].[Trail] ([Trail_ID])
GO
