SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CW1].[TrailFeatures](
	[TrailID] [int] NOT NULL,
	[FeaturesID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [CW1].[TrailFeatures] ADD PRIMARY KEY CLUSTERED 
(
	[TrailID] ASC,
	[FeaturesID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [CW1].[TrailFeatures]  WITH CHECK ADD FOREIGN KEY([FeaturesID])
REFERENCES [CW1].[Features] ([FeaturesID])
ON DELETE CASCADE
GO
ALTER TABLE [CW1].[TrailFeatures]  WITH CHECK ADD FOREIGN KEY([TrailID])
REFERENCES [CW1].[Trail] ([TrailID])
ON DELETE CASCADE
GO
