SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- User Table
CREATE TABLE [CW2].[User] (
    [UserID] [int] IDENTITY(1,1) NOT NULL,
      NOT NULL,
      NOT NULL CHECK ([Role] IN ('Guest', 'User', 'Admin')),
    CONSTRAINT PK_User PRIMARY KEY CLUSTERED ([UserID] ASC),
    CONSTRAINT UQ_User_Email UNIQUE ([EmailAddress] ASC)
) ON [PRIMARY];
GO